// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuufpfNaIHo3B657Q5iVHYmUNbG2xTSCs',
    appId: '1:703567434324:web:c3f9b4e6c8d2a9a13b13c1',
    messagingSenderId: '703567434324',
    projectId: 'my-application-1a3fe',
    authDomain: 'my-application-1a3fe.firebaseapp.com',
    databaseURL: 'https://my-application-1a3fe-default-rtdb.firebaseio.com',
    storageBucket: 'my-application-1a3fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuufpfNaIHo3B657Q5iVHYmUNbG2xTSCs',
    appId: '1:703567434324:android:14823381b27b0a823b13c1',
    messagingSenderId: '703567434324',
    projectId: 'my-application-1a3fe',
    databaseURL: 'https://my-application-1a3fe-default-rtdb.firebaseio.com',
    storageBucket: 'my-application-1a3fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgRVXVAe712hp5yWUCEXiJ1IS_iB5F2As',
    appId: '1:703567434324:ios:269b67b5565b5a643b13c1',
    messagingSenderId: '703567434324',
    projectId: 'my-application-1a3fe',
    databaseURL: 'https://my-application-1a3fe-default-rtdb.firebaseio.com',
    storageBucket: 'my-application-1a3fe.firebasestorage.app',
    iosClientId: 'com.example.trindifyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgRVXVAe712hp5yWUCEXiJ1IS_iB5F2As',
    appId: '1:703567434324:ios:269b67b5565b5a643b13c1',
    messagingSenderId: '703567434324',
    projectId: 'my-application-1a3fe',
    databaseURL: 'https://my-application-1a3fe-default-rtdb.firebaseio.com',
    storageBucket: 'my-application-1a3fe.firebasestorage.app',
    iosClientId: 'com.example.trindifyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuufpfNaIHo3B657Q5iVHYmUNbG2xTSCs',
    appId: '1:703567434324:web:c3f9b4e6c8d2a9a13b13c1',
    messagingSenderId: '703567434324',
    projectId: 'my-application-1a3fe',
    authDomain: 'my-application-1a3fe.firebaseapp.com',
    databaseURL: 'https://my-application-1a3fe-default-rtdb.firebaseio.com',
    storageBucket: 'my-application-1a3fe.firebasestorage.app',
  );
}
